### ISSUE TITLE
Importing test library 'Selenium2Library' failed: ImportError: cannot import name GLOBAL_VARIABLES

### ISSUE THREAD

**Issue by Tset-Noitamotua** [xyb/robotframework-debuglibrary#13]
When  I call `Import Library` in *rfshell* I am getting following error:

```cmd
> import library  Selenium2Library
< keyword: import library  Selenium2Library
! Importing test library 'Selenium2Library' failed: ImportError: cannot import name GLOBAL_VARIABLES

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\Selenium2Library\__init__.py", line 2, in <module>
    from keywords import *
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords\__init__.py", line 1, in <module>
    from _logging import _LoggingKeywords
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords\_logging.py", line 3, in <module>
    from robot.variables import GLOBAL_VARIABLES
PYTHONPATH:
  C:\Python27\Scripts
  C:\Windows\SYSTEM32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\win32
  C:\Python27\lib\site-packages\win32\lib
  C:\Python27\lib\site-packages\Pythonwin
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
>
```

**Comment by Tset-Noitamotua** [comment]
Sorry. My fault. I used outdated Selenium2Library 1.6.0
After updating on recent version 1.7.4 there is no error any more.
